defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true

plugins:
  - jemoji
  - jekyll-include-cache
  - _plugins/purescript

markdown: kramdown
highlighter: rouge
    kramdown:
      input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# multilang
languages: ['ja', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false