defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true

plugins:
  - jemoji
  - jekyll-include-cache
  - purescript.rb

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# multilang
languages: ['ja', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false
url: https://xc-jp.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/blog-posts" # the subpath of your site, e.g. "/blog"
repository: "xc-jp/blog-posts"